### ISSUE TITLE
Rope rename

### ISSUE THREAD

**Issue by danielnowakowski** [python-rope/rope#257]
I've observed that rename runs very slow when it is intended to rename frequent symbol. Please look at the example below:

```
def abc(param):
    print(param)


if __name__ == '__main__':
    abc('test')
```

and I want to rename name of the function `abc`.

In my project, I have about 150 files where `abc` appears somehow, but only text in current file should be renamed. Other occurrences are not adequate to be renamed.

If I change manually name of the function to `test_fun`, which is unique name in the project, rename returns result immediately.

Can we fix it somehow?

**Comment by soupytwist** [comment]
I'm afraid this is due to uncertainty in rope knowing which symbols refer to the `abc` you are renaming. IIRC, it will skip files that don't contain the symbol being renamed, which is why it is much faster in your second case-- for the first, however, the library is not able to know for sure that the `abc` in that file is not the same without analyzing it.

There *is* work that can be done to improve this, but it's a complex problem. Sorry to not have a better answer.
