### ISSUE TITLE
Syntax error at "nonlocal" keyword

### ISSUE THREAD

**Issue by yoshihikoueno** [python-rope/rope#275]
If a code contains "nonlocal" statement, then rope will complain that it's invalid syntax.
I know that rope offers "partial python3 support", so I understand this phenomenon.

I wrote this just to let the developers know about it.

**Comment by lieryan** [comment]
Can't reproduce this in Python 3.8 with latest rope. This is likely because you're running rope on a Python version that does not support `nonlocal` syntax.

`rope` doesn't actually parse Python code, instead it relies on the standard library's `ast` module to do the parsing. `SyntaxError` is usually raised by the `ast.parse()`. For the most part, barring any special behaviours, rope would usually automatically support any new syntax that the Python version that runs rope actually supports (and it will only support whatever that Python version actually supports). 

That means if your editor integration is running `rope` using Python 2.7, which doesn't support `nonlocal` syntax, it won't be able to parse that. Try to see if you can upgade the Python version used by your editor to a version that supports `nonlocal` syntax (i.e. 3.0 or higher).
