### ISSUE TITLE
Rope does not support extract method on expressions with Inline Assignment (walrus operator)

### ISSUE THREAD

**Issue by rubendibattista** [python-rope/rope#357]
I get a syntax error on something like this:

```
if match := cls._REGEX_PATTERN.match(field.name):
    pass
```

**Comment by lieryan** [comment]
Rope itself doesn't support walrus operator when refactoring, only during renaming operation; but that shouldn't result in a SyntaxError. If you received a SyntaxError, that's likely not because of rope itself, but rather the version of Python that you're running rope with. rope uses Python's own builtin `ast` module to parse Python, walrus operator is Python 3.8 and higher, so you need to configure your editor to run rope with Python 3.8 or higher to handle this syntax.

**Comment by lieryan** [comment]
Support for requiring walrus operator seems to have already been added in https://github.com/python-rope/rope/commit/4871928f30f3dfce5a22964e76f3c7562883304b

I'll need to check if there's still any issues refactoring the aforementioned sample code.

**Comment by lieryan** [comment]
Confirmed reproducible test case (rope 0.19.0, Python 3.8):

```
if match := _REGEX_PATTERN.match(field.name):
    pass
```

When Extracting Method on `match := _REGEX_PATTERN.match(field.name)`, this produces Syntax Error because rope was trying to parse the snippet `match := _REGEX_PATTERN.match(field.name)` which is a valid Python in expression context, but not in a statement context.

Expected behavior should probably be something like so:

```
def funcname(field):
    return match := _REGEX_PATTERN.match(field.name)

if match := funcname(field):
    pass
```

**Comment by rubendibattista** [comment]
Thanks @lieryan for getting a look to this!
