### ISSUE TITLE
Command Line Tool 

### ISSUE THREAD

**Issue by lalmei** [python-rope/rope#512]
**Is your feature request related to a problem? Please describe.**

Would like to use rope from the terminal 

**Describe the solution you'd like**

Run commands like rope rename "test" "test_do"  <path/to/files> 

**Describe alternatives you've considered**

**Additional context**

**Comment by lieryan** [comment]
Hi @lalmei, thanks for your interest in rope. Rope is primarily intended for use with an IDE/text editor. So currently there's no officially supported CLI for rope and there's no plan for implementing an official CLI for rope.

You have a couple options for using rope from the terminal.

You might want to try [roper](https://github.com/beat-no/roper), which is a CLI refactoring tool that uses rope. roper doesn't support all of rope's functionalities, but it supports some basic operations like renaming and moving modules. I never used it, but if you do have some success with it, please consider documenting your experience in [rope's Wiki](https://github.com/python-rope/rope/wiki/How-to-use-Rope-in-my-IDE-or-Text-editor%3F).

Second option is that you can just call rope API and functions interactively from an Python/IPython shell. It takes some getting used to, but for basic functionalities it is not too onerous. [Rope's documentation](https://rope.readthedocs.io/en/latest/library.html#rename) should help you get an overview how to use rope API.

**Comment by lalmei** [comment]
Thanks for the thorough response. I will check out `roper` and see if they need help. But I still feel the project would get more traction in the plugin community with a command-line tool. Let me know if you change your mind. Someone could quickly wrap some of the main commands with a tool like [typer.](https://typer.tiangolo.com/). Anyways, enjoying it as is too!

**Comment by lieryan** [comment]
Can you elaborate what kind of plugin project are you working on if you are able to disclose it?

If you are looking to write an IDE/text editor plugin but the plug-in cannot can rope directly as a Python library, what I would recommend instead is to integrate using [pylsp-rope](https://github.com/python-rope/pylsp-rope). Using pylsp-rope allows you to integrate IDE/editor by calling rope functionalities over JSON-RPC. pylsp will be running as a subprocess or a daemon process, and the plugin will be communicating just over relatively simple plaintext protocol via either TCP port or stdin/stdout.

Rope is mainly designed for interactive IDE/text editor integrations, most of its API usually require you to pass in file offsets, which really only makes sense if you're in a text editor/IDE with mouse/keyboard cursor to select part of text. Additionally, many functionalities requires in-memory caching for performance reasons, and a CLI process that dies with every invocation are going to be much slower than a persistent process. All these factors makes it hard to recommend using Rope via CLI since it's usually going to be suboptimal.
