### ISSUE TITLE
Support Python 3.3+

### ISSUE THREAD

**Issue by gotgenes** [python-rope/rope#57]
Modernize rope to install and run on Python 3 versions 3.3 and newer. See [python-future](http://python-future.org/) (prefered) or [six](https://pythonhosted.org/six/) for a single-codebase route to support Python 2 and Python 3.

**Comment by hayd** [comment]
Is this still in the air?

To get the ball rolling... I had a quick go towards py 2 and 3 compatibility in #115. Whilst the tests don't pass python 3 yet, they at least run. I think they are pretty non-intrusive changes, no dependencies and they doesn't break python 2.

**Comment by gotgenes** [comment]
Some other overlapping projects would be [baron](https://github.com/Psycojoker/baron/) and/or [redbaron](https://github.com/Psycojoker/redbaron/). One interesting thing is psycojoker/baron#61, which posits lib2to3 could be used to span both Python 2 and Python 3 syntax trees.

**Comment by hayd** [comment]
@gotgenes interesting! [yapf](https://github.com/google/yapf) uses lib2to3 to make a similar F-ishST (ast + spliced in comments).

**Comment by Psycojoker** [comment]
Hello (baron author's here),

Another option you might want to consider is to take a look at what jedi is doing right now. The author is writing a parser also based on lib2to3 (which might already be finished) with a scope way closer to what rope is trying to achieved (adding static analysis to the python AST).

On my side I haven't had the time to explore the lib2to3 path since I'm horribly busy with other project. But, AFAIK, lib2to3 is the most powerful, solid, optimized and supported AST that works for both python 2 and 3 available right now. It's in the standard python lib and has been written by Guido himself.

One interesting point that came out of all similar discussion that I've had with people of jedi and astroid (pylint) is that we are all basically try to build our own AST (from scratch of from python's one) and that is would be very interesting to try to create a common base for all of us to avoid reinventing the wheel all the time, especially since it's a tedious task (but I don't know if Baron would fit here, I have very special needs).

Cheers,

**Comment by gotgenes** [comment]
> One interesting point that came out of all similar discussion that I've had with people of jedi and astroid (pylint) is that we are all basically try to build our own AST (from scratch of from python's one) and that is would be very interesting to try to create a common base for all of us to avoid reinventing the wheel all the time, especially since it's a tedious task (but I don't know if Baron would fit here, I have very special needs).

Great to have a reply from you, @Psycojoker! Where is this discussion taking place?

**Comment by Psycojoker** [comment]
> Great to have a reply from you, @Psycojoker! Where is this discussion taking place?

My bad, totally forgot the links in my previous post.

The mail from the jedi author talking about his works: https://mail.python.org/pipermail/code-quality/2014-November/000382.html

This was in the first thread of this month on the "code-quality" mailing list: https://mail.python.org/pipermail/code-quality/2014-November/thread.html#382 "RedBaron, a bottom-up refactoring lib/tool for python".

You can subscribe here: https://mail.python.org/mailman/listinfo/code-quality

**Comment by anarcat** [comment]
it seems there was some progress here... does rope work with python3 yet? in 0.10.2, i get errors if only with the print() function...

**Comment by emacsway-qarea** [comment]
I've added some Py3k fixes in #133 . Currently remains only failures=50, errors=40

**Comment by emacsway** [comment]
I've added some Py3k fixes in #133 . Currently remains only failures=50, errors=40
