### ISSUE TITLE
Killed unit tests can leave a sample_project folder in the top-level folder

### ISSUE THREAD

**Issue by edreamleo** [python-rope/rope#589]
This has happened several times, but my notes don't tell me how to reproduce the bug. 

Hmm. I bet I know what happened. I probably killed the console running the tests, thereby randomly preventing a `tearDown` method from executing.

`testutils.sample_project` special-cases posix platforms. Perhaps this bug only bites on Windows.  Or perhaps projects could be created in a tmp folder.

Investigation shows that *many* `setUp` and `tearDown` methods create and destroy the `sample_projects` folder. It's non-trivial to verify that each `tearDown` method destroys the folder created by `setUp`.

So it might be safer to define a `ProjectTestCase` class whose `setUp` and `tearDown` methods call `testutils.sample_project` and `testutils.remove_project` respectively. Subclasses would then be free of managing the project folder themselves.

**Comment by lieryan** [comment]
This never happens in Linux because in Linux, the leftover sample_project() is actually left in `/tmp`. 

We should update `sample_project()` to use either the stdlib's [tempfile.TemporaryDirectory()](https://docs.python.org/3/library/tempfile.html) or [pytest's `tmpdir` fixture](https://docs.pytest.org/en/6.2.x/tmpdir.html).

I think `tempfile.TemporaryDirectory()` is going to be easier to implement since `sample_project()` can be used on legacy unittests that doesn't use pytest' fixture mechanisms.

**Comment by edreamleo** [comment]
@lieryan Another alternative: add `sample_project` to `.gitignore`.

**Comment by lieryan** [comment]
This should now be fixed in #596, @edreamleo would you be able to test on Windows?

**Comment by edreamleo** [comment]
@lieryan Thanks!

**Comment by edreamleo** [comment]
@lieryan I ran and interrupted pytest several times on Windows. The sample_project folder never persisted.

But this doesn't seem like much of a test :-) Do you have any ideas about how to strengthen the test?

**Comment by lieryan** [comment]
That should be good. Just keep an eye and report back if the issues ever returns.

**Comment by edreamleo** [comment]
@lieryan will do.
