### ISSUE TITLE
Create class RopeTest(unittest.TestCase)

### ISSUE THREAD

**Issue by edreamleo** [python-rope/rope#591]
A common base class for Rope's test classes would eliminate or simplify `setUp` and `tearDown` methods.

Two classes have useless `setUp` and `tearDown` methods:
```python
def setUp(self):
    super().setUp()

def tearDown(self):
    super().tearDown()
```

8 classes have identical `setUp` methods:
```python
def setUp(self):
    super().setUp()
    self.project = testutils.sample_project()
```

39 classes have class-specific `setUp` methods, but many of these `setUp` methods are similar.
In particular, most `setUp` methods contain:
```
self.project = testutils.sample_project()
self.pycore = self.project.pycore
```
These lines could be included in `RopeTest.setUp`.
It might make sense to generalize `RopeTest.setUp` further.

42 classes have identical `tearDown` methods:
```python
def tearDown(self):
    testutils.remove_project(self.project)
    super().tearDown()
```
Only 6 classes have unusual `tearDown` methods.

**Summary**

A common base class for all of Rope's test classes would eliminate duplication and emphasize real differences between tests.

**Comment by edreamleo** [comment]
@lieryan I suggest the following organization:

- `setUpClass`: create the `sample_project` directory.
- `setUp`: wipe that directory, then init.
- `tearDown`: not needed.
- `tearDownClass`: (Optional: remove the `sample_project` directory.

Convert all functions in `ropetest.testutils` to methods of the `RopeTest` class.

**Comment by lieryan** [comment]
I'm not too keen on rewriting working legacy tests just for the sake of rewriting tests, but if you want to do this anyway, since we're all in into pytest, pytest have much better solution for this: https://docs.pytest.org/en/7.1.x/how-to/unittest.html

autouse fixture should create empty sample project and also cleanup (if you use pytest's temp directory mechanism, this isn't actually necessary as pytest and - to some degree - the OS will do the clean up).

**Comment by edreamleo** [comment]
@lieryan Thanks for the link. I'll take a look

I understand your reluctance. Even if simpler, the new tests might not be as strong as the old.
