### ISSUE TITLE
Fix a valid mypy complaint

### ISSUE THREAD

**Issue by edreamleo** [python-rope/rope#662]
Without a `type:ignore` comment mypy issues the following warning:

     rope\base\pyobjects.py:304: error: "_PyModule" has no attribute "get_name"

The code in question is `pyobjects._PyModule.absolute_name`:
```python
@property
def absolute_name(self) -> str:
    return self.get_name()  # type:ignore
```
This error appears to be valid, but Rope's unit tests do not expose this bug.

Here is the class hierarchy.  All classes appear in pyobjects.py:
```
class _PyModule(PyDefinedObject, AbstractModule):
class PyDefinedObject:
class AbstractModule(PyObject)
class PyObject:
```
None of these classes has a `get_name` member.

Four (passing) unit tests call `pyobjects._PyModule.absolute_name` indirectly:
```python
test_repr_pyobjectsdef_pymodule
test_repr_pyobjectsdef_pymodule_without_associated_resource
test_repr_pyobjectsdef_pypackage
test_repr_pyobjectsdef_pypackage_without_associated_resource
```
These tests will fail if `pyobjects._PyModule.absolute_name` raises an exception.

These tests pass because the tests exercise only the `pyobjectsdef.PyModule`  and `pyobjectsdef.PyPackage` classes. These classes:
- are subclasses of `_pyobjects._PyModule`.
- *do* have `get_name` members.

For example, here is the class hierarchy of `pyobjectsdef.PyModule`:
```
class PyModule(pyobjects.PyModule):
class PyModule(_PyModule):  # pyobjects._PyModule
```
**Summary**

mypy has exposed a potential crasher.

**Comment by lieryan** [comment]
> mypy has exposed a potential crasher.

I don't think there is a practical risk of crashing here because _PyModule is actually an abstract class, it's never meant to be instantiated. Moreover `absolute_name()` is currently only meant to be used for `__repr__`, which is only used for debugging or interacting with Rope objects in REPL. 

If this has been a production code, I'd have made this an abc to enforce that all subclasses implements get_name(), but I wasn't too keen on making it a hard requirement for subclasses to implement a debugging helper method.

**Comment by edreamleo** [comment]
@lieryan I agree, this is no big deal.
