### ISSUE TITLE
Any prerequisites for a new release (> 1.6.0)?

### ISSUE THREAD

**Issue by tkrabel-db** [python-rope/rope#729]
### Description

Hi @lieryan ,

Are there any prerequisites for getting a new release out? Happy to help!

**Comment by lieryan** [comment]
Hi @tkrabel-db, not quite sure what you meant by "prerequisites". Can you elaborate?

**Comment by tkrabel-db** [comment]
@lieryan actually, what I wanted to ask is: when will there be a new release? :)

**Comment by lieryan** [comment]
The release schedule is that there should be a release around the 15th of each month. But it also depends on whether there's actually any changes available for that month and the exact release date may vary based on my personal availability or if there's a blocking issue. If the 15th passes and I didn't make a release while there's something pending and no obvious blockers, it's usually because I forgot about it, so feel free to poke me.
